### ISSUE TITLE
No way to set the multisig tx expiration time. 

### ISSUE THREAD

**Issue by jabo38** [symbol/symbol-desktop-wallet#1203]
It seems like right now the wallet doesn't keep multisig txs in memory for very long; maybe 2 hours or something like that. (If I'm wrong, we can close this issue)

For some mulitisg signers, 2 hours means they won't get a lot of txs signed. 

If we wanted to get really fancy, in the settings menu, there could be a setting for "set time for multisig tx expiration".  In which case it would be defaulted at 48 hours or even 2880 minutes. And if somebody wanted to set a custom time, they could reduce that to 1 hour or even 1 minute. 

Here is a possible solution but there are many. 

![image](https://user-images.githubusercontent.com/10395907/108789738-85ea1780-7540-11eb-8a62-a71a1e8620bc.png)

Or we could maybe consider changing the default time to 48 hours too and no settings option.

**Comment by myxmaster** [comment]
Or you put the deadline in the TX form, and then maybe hide that behind an "advanced" checkbox.

By the way, this is kind of related to #545, because when the deadline for multisig is 48h by default, then the timestamp for multisig-transactions will always display wrong, as long as that issue is not solved.

**Comment by jabo38** [comment]
I said 2880 but I realized that 48 hours is actually 5760 blocks

**Comment by cryptoBeliever** [comment]
@jabo38 @bassemmagdy 
The aggregate transactions deadline was changed now to 48h. Do you think that the time limit in settings will be still useful?

**Comment by bassemmagdy** [comment]
@cryptoBeliever @jabo38 I believe that one should've been closed when we updated the aggregate deadline to 48H
