### ISSUE TITLE
When importing a Mnemonic, there is a copy button where a person is supposed to paste their 24 words

### ISSUE THREAD

**Issue by jabo38** [symbol/symbol-desktop-wallet#1474]
When somebody is making a new mnemonic and they get their 24 words for the first time, it is great to have a copy button. But when they are restoring a passphrase, they will be pasting it in, so a copy button isn't needed on that screen.

**Comment by jabo38** [comment]
Maybe if there was a need of the copy button, it could be after all 24 words were entered, it might be nice to have it appear then maybe.

**Comment by cryptoBeliever** [comment]
@AnthonyLaw when we use "Paste" button and we don't have all 24 words to paste we lose input focus. To restore it we have to click in very small area of "Enter a mnemonic passphrase". Could we improve it somehow (by not losing input focus or allow to click in any place "Enter a mnemonic passphrase" area to restore focus).
Video: https://share.getcloudapp.com/P8u9BYLW

**Comment by cryptoBeliever** [comment]
After changes from https://github.com/symbol/symbol-desktop-wallet/pull/1617 works fine now :+1:

**Comment by cryptoBeliever** [comment]
Done in integration.
