### ISSUE TITLE
Harvesting - Errors setting up vrf and remote keys #1328

### ISSUE THREAD

**Issue by surekabpm** [symbol/symbol-desktop-wallet#1601]
I'm having trouble setting up a vrf and voting key: (my account is a 2of2 multisig account with 3 cosigs)
Trying to set up Remote and VRF keys using the symbol desktop wallet (not the 'Link all keys' but individually linking the remote and vrf key) gets me this error and a funds lock that doesn't do anything
Errors:

Validation failed because hash is not present in cache
Failed to sign transaction, reason: Failure_LockHash_Unknown_Hash
Funds lock transaction: http://explorer.symbolblockchain.io/transactions/7165F34C65DB4387BFD363C656E61EFABBD841B0831F9E0F6540855C31AF2B13

**Comment by cryptoBeliever** [comment]
Duplicate
