### ISSUE TITLE
Ledger signing error v1.0.5

### ISSUE THREAD

**Issue by u2yasan** [symbol/symbol-desktop-wallet#1620]
When I co-signing a transaction with XYM Wallet v1.0.2 on Ledger Nano X I got the following erro message:
Failed to sign transaction, reason: dlopen(/var/folders/vw/2r6g3gfd27g3cd20fyvwm17r0000gn/T/.io.nem.symbol.desktop-wallet.GaBy5X, 1): no suitable image found.  Did find:
	/var/folders/vw/2r6g3gfd27g3cd20fyvwm17r0000gn/T/.io.nem.symbol.desktop-wallet.GaBy5X: code signature in (/var/folders/vw/2r6g3gfd27g3cd20fyvwm17r0000gn/T/.io.nem.symbol.desktop-wallet.GaBy5X) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/var/folders/vw/2r6g3gfd27g3cd20fyvwm17r0000gn/T/.io.nem.symbol.desktop-wallet.GaBy5X: stat() failed with errno=316

I use symbol-desktop-wallet-mac-1.0.5.dmg.
I can co-signing symbol-desktop-wallet v1.0.4.

**Comment by NikolaiB** [comment]
WTR:

1. Try to create a new profile with Ledger
Result: on the profile name and password you are getting error

![image](https://user-images.githubusercontent.com/11311924/126963244-f955635d-e060-44ee-96fe-a2f83dd23338.png)

**Comment by coiki** [comment]
Incoming fix

**Comment by cryptoBeliever** [comment]
Fixed, build replaced. @u2yasan you can verify.
